name: Question
description: Ask questions about gnet.
title: "[Question]: "
labels: ["question", "help wanted"]
body:
  - type: markdown
    id: tips
    attributes:
      value: |
        ## Before you go any further
        - Please read [<u>*How To Ask Questions The Smart Way*</u>](http://www.catb.org/~esr/faqs/smart-questions.html) ( Chinese translation: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)) before you file an issue formally.
        - Keep in mind that there is always welcome to ask questions on [Discord](https://discord.gg/UyKD7NZcfH).
        - First of all, visit our [website](https://gnet.host) and [Github Org](https://github.com/gnet-io) for docs and examples.
        - Make sure what you're looking for here is an issue rather than a [discussion](https://github.com/panjf2000/gnet/discussions/new/choose).
  - type: checkboxes
    id: checklist
    attributes:
      label: Actions I've taken before I'm here
      description: Make sure you have tried the following ways to get the answer of your problem.
      options:
        - label: I've thoroughly read the documentations about this problem but still have no answer.
          required: true
        - label: I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
          required: true
        - label: I've searched the internet for this problem but didn't find anything helpful.
          required: true
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Questions with details
      description: What do you want to know?
      placeholder: Describe your question with critical details here.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code snippets (optional)
      description: Illustrate your question with source code if needed.
      render: go
